### ISSUE TITLE
可否将窗口置于桌面下方

### ISSUE THREAD

**Issue by PDY111** [EnderWolf006/ElectronClassSchedule#1]
就是那种`win+d`也消除不了，类似于wallpaper engine和 Visual Studio等的启动页面 一样的

**Comment by EnderWolf006** [comment]
把 `resources/app/main.js` 中的第28行删掉试试，我也再研究一下能不能用electron实现类似效果
![Snipaste_2024-02-24_18-46-15](https://github.com/EnderWolf006/ElectronClassSchedule/assets/152008081/8acab94c-4641-409f-bc16-f08da19d4a48)

**Comment by PDY111** [comment]
我将这一行注释和alwaysOnTop改为false，可以关闭置顶显示，但没能解决`win+D`其消失的问题
<img width="934" alt="image" src="https://github.com/EnderWolf006/ElectronClassSchedule/assets/110529327/9991dfcd-8421-4d82-8e99-ba95548eb49f">
