### ISSUE TITLE
[Bug]特定场景时计时模块时间更新停滞、被覆盖

### ISSUE THREAD

**Issue by AlephZHAO** [EnderWolf006/ElectronClassSchedule#12]
1.系统环境/涉及软件:
系统:`Windows10 21H2 内部版本 19044.4170`
(希沃魔改Windows10系统)
软件:`希沃白板5.2.4.6909`
2.问题描述/复现:
I.当希沃白板扫码/账密登陆后，弹出的课件列表会导致电子课表的**计时模块停滞**，当**移动课件列表窗口、点击课件列表选项和双击打开课件**后，计时恢复到正确时间并继续计时
II.当使用**希沃白板手机APP向电脑的希沃白板投屏图片**时，整个电子课程表会被直接**覆盖**，退出投屏图片后，电子课程表恢复正常运行/展示
3.附件视频展示问题
（暂时只有问题`1-I`的复现展示视频）

https://github.com/EnderWolf006/ElectronClassSchedule/assets/103933601/a1fb4a97-18c9-4447-a56c-52ba18a1fb5b

4.**感谢作者制作并开源软件！不着急修BUG加功能，以学业为主哈，不要耽误了高考**

**Comment by AlephZHAO** [comment]
> I 应该与电子课表无关，猜测是希沃白板把背景截图冻结了 II 电子课表窗口置顶已经设置最高了，没有办法

感谢回复！
这些问题可能暂时没有什么解决方案，看看后续有没有什么新的思路来解决这两个问题吧，我暂时先不关闭这个issue了

**Comment by PDY111** [comment]
在taskmgr中设置优先级为高试一下

**Comment by EnderWolf006** [comment]
应该是没什么好办法，已经设置最高级了
