### ISSUE TITLE
添加新功能

### ISSUE THREAD

**Issue by jizilin6732** [EnderWolf006/ElectronClassSchedule#13]
1. 加天气预报（虽然没啥用）
2. 优化倒数日精度（2.856天这样的）
3. 在某科关闭上课计时

**Comment by PDY111** [comment]
首先，1不符合这个软件的初衷，你可以找其他软件
其次，2这个会让更多人不满意(毕竟大多数人不喜欢小数
最后，3你可以手动该或者可以提个pr
