### ISSUE TITLE
安化一中电位提出的新功能与意见

### ISSUE THREAD

**Issue by jizilin6732** [EnderWolf006/ElectronClassSchedule#15]
1.数学老师用希沃轻白板时上面容易影响触控
2.建议早自习可以隐藏课表或者把早自习单独列为一节课，有的时候会挡住课件
3.建议把日期改成幼圆字体的周一
4.建议添加值日生功能
5.课表修改没搞清楚，经常改了第二天一大堆报错课程

**Comment by ziqianou** [comment]
能发一下你配置文件吗？
