### ISSUE TITLE
[功能建议] 支持修改课表尺寸/根据屏幕分辨率灵活调整大小

### ISSUE THREAD

**Issue by RoboMico** [EnderWolf006/ElectronClassSchedule#19]
课表大小似乎是直接以像素为单位的，在我家用机1920x1080的屏幕上效果还行，但是学校电脑屏幕是1600x900会导致课表看起来有点大：
![image](https://github.com/EnderWolf006/ElectronClassSchedule/assets/59791306/203af6bd-8ae6-427a-b902-081523ce1ebc)
![屏幕截图 2024-04-02 215011](https://github.com/EnderWolf006/ElectronClassSchedule/assets/59791306/81dd1f0e-63d9-4e8e-aabf-ccfab9cfc24d)

建议添加根据屏幕分辨率自动调整课表大小的功能，比如可以设定课表长度最长占整个屏幕的百分之多少，实在不济的话加一个手动调整大小也是可以的

**Comment by EnderWolf006** [comment]
可以在配置文件中调整大小

**Comment by EnderWolf006** [comment]
还有就是1600x900屏幕大小还需要调到125%吗，调到100%试试

**Comment by cc1287** [comment]
我自己是这样改大小的
![image](https://github.com/EnderWolf006/ElectronClassSchedule/assets/163511468/62bb8c88-1352-4bfb-99a3-6861d60f704e)
