### ISSUE TITLE
[Enhancement] 可否在课程表上添加分隔符

### ISSUE THREAD

**Issue by DryIce-cc** [EnderWolf006/ElectronClassSchedule#3]
分隔符作用和课间一样，但显示在课程表上，用于分割上午/下午/晚上的课程。
![效果像这样](https://github.com/EnderWolf006/ElectronClassSchedule/assets/165131008/14e74fe1-6905-439a-bf1e-9d6dce93f052)

**Comment by PDY111** [comment]
close一下

**Comment by EnderWolf006** [comment]
已更新
