### ISSUE TITLE
[Suggestion] 开启GitHub Discussions功能

### ISSUE THREAD

**Issue by AlephZHAO** [EnderWolf006/ElectronClassSchedule#45]
可以开启本项目的GitHub Discussions功能，方便大家对本项目进行高效讨论

### GitHub Discussions官方简介：
>  GitHub Discussions 是一个围绕开源或内部项目为社区提供协作沟通的论坛。 与 GitHub Issues 不同，讨论用于需要透明和可访问的对话，但不需要在项目上进行跟踪，并且与代码无关。 讨论使公共论坛中能够进行流畅、公开的对话。
>  通过连接和提供更集中的区域来连接和查找信息，讨论为更多协作对话提供了空间。

GitHub Discussions 快速入门:https://docs.github.com/zh/discussions/quickstart

**Comment by EnderWolf006** [comment]
已开启
