### ISSUE TITLE
添加可视化编辑课程功能

### ISSUE THREAD

**Issue by wess09** [EnderWolf006/ElectronClassSchedule#5]
下面是GPT生成的逻辑
`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Schedule Config Editor</title>
    <style>
        /* CSS 样式可以在此编辑 */
        body {
            font-family: Arial, sans-serif;
        }
        label {
            display: block;
            margin-bottom: 5px;
        }
        input[type="text"] {
            width: 100%;
            padding: 5px;
            margin-bottom: 10px;
            box-sizing: border-box;
        }
        textarea {
            width: 100%;
            height: 100px;
            padding: 5px;
            margin-bottom: 10px;
            box-sizing: border-box;
        }
        #output {
            width: 100%;
            height: 200px;
            padding: 10px;
            box-sizing: border-box;
            border: 1px solid #ccc;
            overflow-y: auto;
        }
    </style>
</head>
<body>
    <h2>Schedule Config Editor</h2>
    <form id="configForm">
        <label for="countdown_target">Countdown Target:</label>
        <input type="text" id="countdown_target" name="countdown_target">
        
        <label for="subject_name">Subject Name:</label>
        <textarea id="subject_name" name="subject_name"></textarea>
        
        <label for="timetable">Timetable:</label>
        <textarea id="timetable" name="timetable"></textarea>
        
        <label for="daily_class">Daily Class:</label>
        <textarea id="daily_class" name="daily_class"></textarea>
        
        <label for="css_style">CSS Style:</label>
        <textarea id="css_style" name="css_style"></textarea>
        
        <button type="button" onclick="saveConfig()">Save Config</button>
    </form>
    
    <div id="output"></div>
    
    <script>
        // JavaScript 代码可以在此编辑
        var scheduleConfig = JSON.parse(JSON.stringify(_scheduleConfig));

        // Function to save the edited config
        function saveConfig() {
            var form = document.getElementById('configForm');
            var formData = new FormData(form);
            var config = {};

            for (var pair of formData.entries()) {
                config[pair[0]] = pair[1];
            }

            // Convert textarea values to objects if applicable
            ['subject_name', 'timetable', 'daily_class', 'css_style'].forEach(key => {
                if (config[key]) {
                    try {
                        config[key] = JSON.parse(config[key]);
                    } catch (error) {
                        console.error("Error parsing JSON for " + key + ": " + error);
                    }
                }
            });

            // Update output
            var outputDiv = document.getElementById('output');
            outputDiv.textContent = JSON.stringify(config, null, 2);
        }
    </script>
</body>
</html>`

**Comment by EnderWolf006** [comment]
大佬好提个Pr😘
