### ISSUE TITLE
希望增加修临时更换课表的设置

### ISSUE THREAD

**Issue by MYS-KISO** [EnderWolf006/ElectronClassSchedule#8]
如题，已经在b站上留下过评论了，如果有空的话还是希望能完善一下下这个功能，比如可以指定某一天更换为休息天/其他日的课表，也希望作者要以学业为主哈，不要耽误了高考呐。
【给后面看到这个issue的人】作者在b站上的回复是“暂时还没有这个功能，不过可以通过‘计时矫正’这个功能调快或调慢几天，86400秒为一天”

**Comment by HappyTigerV** [comment]
我实现了这个功能，已经提交PR，但是作者还没merge.
参见[HappyTigerV/ElectronClassSchedule](https://github.com/HappyTigerV/ElectronClassSchedule/)，在releases下载. 值得注意的是，如果下载太慢，**不要**点击releases中的镜像链接，这会下载未修改版的。如果您确实需要加速下载，可以使用以下链接。

[Win10/Win11镜像链接](https://ghproxy.net/https://github.com/HappyTigerV/ElectronClassSchedule/releases/download/latest/Win10_Win11_ElectronClassSchedule.zip)

[Win7/Win8镜像链接](https://ghproxy.net/https://github.com/HappyTigerV/ElectronClassSchedule/releases/download/latest/Win7_Win8_ElectronClassSchedule.zip)

祝您生活愉快！

**Comment by MYS-KISO** [comment]
您好~
***@***.***，后续回复会从上述邮箱发出，感谢您的来信~MYS-KISO//PRy_OS

**Comment by EnderWolf006** [comment]
已经更新了，下载最新版即可
